### ISSUE TITLE
Release a new package with Python 3 support

### ISSUE THREAD

**Issue by djt5019** [yummybian/consistent-hash#8]
Hi, I've been using the `consistent_hash==1.0` library for a little bit now pretty successfully, however, when I tried to use it in a Python 3 application it just fell on it's face.  It turns out there was already work done to properly support Python 3 in #6.

Can you please upload a new version of this library so we can take advantage of the Python 3 support?

**Comment by sontek** [comment]
@yummybian ping

**Comment by djt5019** [comment]
@yummybian pong

**Comment by charmander** [comment]
Why was this closed?

**Comment by djt5019** [comment]
I gave up on it.  I'm no longer working on the project that required this, and there's been no movement on it for over a year.
